name: SQL-Challenge

services:
  postgres:
    image: postgres:17.4-alpine3.21
    container_name: inventory_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory
    ports:
      - "5432:5432"
    volumes:
      - ./preloaded-data:/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql